website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import DomainPer, User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from datetime import datetime

auth = Blueprint('auth',__name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
               
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login_signup.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/update', methods=['GET','POST'])
def update():

    if request.method == 'POST':
        if request.form.get('updateSal'):
            salary = request.form.get('salary')
        
            if len(salary) < 1:
                    flash('Salary is too short!', category='error')
            else:
                salary = request.form.get('salary')
                db.session.query(User).filter(User.id == current_user.id).update({User.salary:salary})
                db.session.commit()
                flash('Salary updated!', category='success')
               
        if request.form.get('domain') :
            if request.form.get('amount').lower()=='yes':
                return redirect(url_for('auth.domainPer'))
            else:
                return redirect(url_for('views.home'))
     
    return render_template("update.html",user=current_user)

@auth.route('/domainPer', methods=['Get','POST'])
def domainPer():
    if request.method == 'POST':
        eating_out =  request.form.get('eating out')
        groceries =  request.form.get('groceries')
        clothes =  request.form.get('clothes')
        bills_and_rent =  request.form.get('bills')
        housing =  request.form.get('housing')
        stationary =  request.form.get('stationary')
        travel = request.form.get('travel')
        entertainment =  request.form.get('entertainment')
        health =  request.form.get('health')
        sport =  request.form.get('sport')
        others =  request.form.get('others')
        if len(eating_out) < 1 or len(groceries)<1 or len(clothes)<1 or len(bills_and_rent)<1 or len(housing)<1 or len(stationary)<1 or len(travel)<1 or len(entertainment)<1 or len(health)<1 or len(sport)<1 or len(others)<1:
            flash('Please enter all the fields!', category='error')
        else:
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.eating_out:eating_out})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.groceries:groceries})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.clothes:clothes})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.bills_and_rent:bills_and_rent})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.housing:housing})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.stationary:stationary})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.travel:travel})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.entertainment:entertainment})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.health:health})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.sport:sport})
            db.session.query(DomainPer).filter(DomainPer.user_id == current_user.id).update({DomainPer.others:others})
            db.session.commit()
            #flash('!', category='error')
            return redirect(url_for('views.home'))
    
    return render_template('domain.html',user=current_user)

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        User.query.filter(User.email.endswith('@example.com')).all()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, user_name=name, password=generate_password_hash(
                password1, method='sha256'), loggedin_date=datetime.now())
            db.session.add(new_user)
            user = User.query.filter_by(email=email).first()
            domain = DomainPer(user_id = user.id)
            db.session.add(domain)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('auth.update')) 

    return render_template("login_signup.html", user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
      {% block head %} {% endblock %}
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
            />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />

        <link rel="stylesheet" text='text/css' href="{{ url_for('static', filename='style.css') }}" />

       
            <title> {% block title %} Home {% endblock %} </title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
              <a href ="#" class ="navbar-brand mb-01 h1"style="font-weight: bold" >FinanceBoss</a> 

              {% if user.is_authenticated %}
        
              <a class="nav-item nav-link" id="home" href="/" >Home</a>
              <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
              <a class="nav-item nav-link" id="update" href="/update" >Update</a>
                        
              
              {% endif %}
              
            </div>
          </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %} 
        {% for category, message in messages %} 
        {% if category =='error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endif %} {% endfor %} {% endif %} {% endwith %}
        
        <div class="conatainer">
            {% block content %} {% endblock %}
        </div>
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous">
        </script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous">
        </script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous">
        </script>
        <script
        type="text/javascript"
        src="{{ url_for('static', filename='index.js') }}">
        </script>
    </body>
</html>

website/templates/domain.html
{% extends "base.html" %} {% block title %}Domain Perentages{% endblock %} {% block content
    %}

  
    {% block head %}
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
 
    <style media="screen">
      
body{
    background-color:  #ab86ce;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
    
}

form{
    height: 1270px;
    width: 500px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 100%;
    margin-top: 13px;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
    margin-bottom: 70px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: black;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}


input{
    display: block;
    height: 50px;
    width: 100%;
    background-color:whitesmoke;
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 18px;
    font-weight: 300;
}
        
::placeholder{
    color: black;
}
button{
    margin-top: 35px;
    width: 80%;
    margin-left: 45px;
    margin-bottom: 20px;
    background-color: rgb(60, 7, 104);
    color:  #fdfdff;
    padding: 15px 0;
    font-size: 14px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
        label{
    display: block;
    margin-top: 10px;
    font-size: 16px;
    font-weight: 500;
}
  

    </style>
    
    {% endblock %}
    
    

<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    
               
               
               
                 <div id="form" class="card-body">
    
    <form method="POST">
         <h2>Domain Values</h2>
         (Enter how much percentage of salary do you want to spend in each domain (your savings are excluded))
      <label>Eating Out</label>
      <input type="number" name="eating out" id="eating out" placeholder="Default : 8% ">
      <label>Groceries</label>
      <input type="number" name="groceries" id="groceries" placeholder="Default : 9% ">
      <label>Clothes</label>
      <input type="number" name="clothes" id="clothes" placeholder="Default : 5% ">
      <label>Bills and Rent</label>
      <input type="number" name="bills" id="bills" placeholder="Default : 15% ">
      <label>Housing</label>
      <input type="number" name="housing" id="housing" placeholder="Default : 7% ">
      <label>Stationary</label>
      <input type="number" name="stationary" id="stationary" placeholder="Default : 3% ">
      <label>Travel</label>
      <input type="number" name="travel" id="travel" placeholder="Default : 10% ">
      <label>Entertainment</label>
      <input type="number" name="entertainment" id="entertainment" placeholder="Default : 5% ">
      <label>Health</label>
      <input type="number" name="health" id="health" placeholder="Default : 9% ">
      <label>Sport</label>
      <input type="number" name="sport" id="sport" placeholder="Default : 5% ">
      <label>Others</label>
      <input type="number" name="others" id="others" placeholder="Default : 12% ">

<button type="submit" class="button">Submit</button>
    </form>
    
    

  </div> 
</body>

{% endblock %}

website/templates/expenses.html
{% extends "base.html" %} {% block title %}Expenses{% endblock %} {% block content
    %}
    
  
  
  {% block head %}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
 
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 150px;
    width: 150px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -70px;
    top: -30px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -80px;
    bottom: -110px;
}
form{
    height: 630px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
    margin-top: 40px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}

label{
    display: block;
    margin-top: 20px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 40px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 2px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 10px;
    margin-bottom: 15px;
    width: 70%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
  h2.heading{
        color: black;    
        }
.header{
      padding: 2px;
    background: #DEDEDE;
    font-size: 12px;
    text-align: center;
        }
        #expense {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 70%;
}

#expense td, #expense th {
  border: 1px solid #ddd;
  padding: 8px;
}

#expense tr:nth-child(even){background-color: #f2f2f2;}
#expense tr:nth-child(odd){background-color: #f3dbff;}

#expense tr:hover {background-color: #ddd;}

#expense th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #343a38;
  color: white;
}
    
    </style>
    
    
  {% endblock %}  

<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    
      <div class="card-body">                   
       <form method="POST">
      <div class="header">
       <h2 class="heading">ADD YOUR EXPENSE HERE</h2>
           </div>
        <div class="form-group">
          <label for="date">Date</label>
          <input type="datetime-local" step="1" class="form-control" id="date" name="date" placeholder="Enter date " />
        </div>
        <div class="form-group">
          <label for="detail">Detail</label>
          <input type="text" class="form-control" id="detail" name="detail" placeholder="Enter Detail"/>
        </div>
        
        <div class="form-group">
            <label for="amount">Amount</label>
            <input type="text" class="form-control" id="amount" name="amount" placeholder="Enter Amount" />
          </div>
          <br />
        
      <div align="center">
        <button type="submit" class="button">Add expense</button>
        <button type="submit" class="button" name="display" id="display" value="display" onclick="window.location.href = '#display_table';">Show Expenditures</button>
      </div>
    </form>
    
    
    </div>
    <div id ="display_table" style="margin-top: 700px; color: rgb(236, 211, 248);"align="center" >
      {% if show %}
      <h2> My Expenses</h2>
      <br>
        <table id = "expense" class="table table-striped" >
            <tr>
                <th>Expense Description</th>
                <th>Amount</th>
                <th>Date</th>
            </tr>
            {% for d in display%}
            <tr>
                <td>{{ d.details }}</td>
                <td>{{ d.amount }}</td>
                <td>{{ d.date }}</td>
            </tr>
            {% endfor %}
        </table>
      {% else %}
      {% endif %}
    </div>
     
  
</body>

    {% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
  %}
  <br>
  <h1 align="center"><u style="text-decoration: underline; text-decoration-style: double ;text-decoration-color: rgb(75, 73, 75);">FinanceBoss</u></h1>
  
  
  {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <style>
    *{box-sizing: border-box;}
    
    body{
    background-color: #ab86ce;
  
}
.background{
  position: absolute;
}
form{
  position: absolute;
}
.column
{
  float: left;
  width: 21.5%;
  padding: 5px;
    margin-right: 20px;
    margin-left: 30px;
    margin-top: 110px;
    position: relative;
  border: 3px solid black; 
}
.row::after
{
content: "";
display: table;
clear: both;
}

img {
    height: 250px;
     width: 100%;
     top: 100px;
   
  }
button{
    position: absolute;
  padding: 16px;
  background-color: rgb(60, 7, 104);
  border-radius: 12px;
  top: 270px;
  left: 90px;
  width: 150px;
 font-size: 16px;
color: whitesmoke;
  }
    
    </style>
  
  {% endblock %}

<body>
  <form method="POST">
  <div class="row">
    <div class="column">
      <img src="https://asset5.scripbox.com/wp-content/uploads/2020/03/expense-ratio-vector.png" width="100%;">
      <button name="add_exp" value="add_exp">Add Expense</button>
  </div>
<div class="column">
      <img src="https://asset5.scripbox.com/wp-content/uploads/2018/02/coffee-can-investing-vector.png" width="100%;">
      <button name="stats" value="stats"> Statistics</button>
  </div>
  <div class="column">
      <img src="https://asset5.scripbox.com/wp-content/uploads/2021/03/invest-rs-1000-every-month-vector.png" width="100%;">
      <button name="advice" value="advice">Advice</button>
  </div>
    <div class="column">
      <img src="https://asset5.scripbox.com/wp-content/uploads/2021/06/goal-based-investing-vector.png" width="100%;">
      <button name="per_goal" value="per_goal">Personal Goals</button>
  </div>
    </div>
  </form>
</body>

  {% endblock %}

website/templates/login_signup.html
{%  extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
    <div class="body1">
    <div class="container">
        <input type="checkbox" id="flip">
        <div class="cover">
          <div class="front">
            <div class="text">
    
              <span class="text-1">FinanceBoss <br></span>
            </div>
          </div>
          <div class="back">
            
          </div>
        </div>
        <div class="forms">
            <div class="form-content">
              <div class="login-form">
                <div class="title">Login</div>

              <form method="POST" action="{{ url_for('auth.login') }}">
                <div class="input-boxes">
                  <div class="input-box">
                    <i class="fas fa-envelope"></i>
                    <input type="text" id ="email" name = "email" placeholder="Enter your email" required>
                  </div>
                  <div class="input-box">
                    <i class="fas fa-lock"></i>
                    <input type="password" id="password" name="password" placeholder="Enter your password" required>
                  </div>
                  
                  <div class="button input-box">
                    <input type="submit" id ="submit" name ="submit" Value="Log In">
                 
                  </div>
                  <div class="text sign-up-text">Don't have an account? <label for="flip">Sigup now</label></div>
                </div>
              </form>
          </div>

            <div class="signup-form">
              <div class="title">Signup</div>

            <form method="POST" action="{{ url_for('auth.sign_up') }}">
                <div class="input-boxes">
                  <div class="input-box">
                    <i class="fas fa-envelope"></i>
                    <input type="text" id="name" name="name" placeholder="Enter your name" required>
                  </div>
                  <div class="input-box">
                    <i class="fas fa-envelope"></i>
                    <input type="text" id="email" name="email" placeholder="Enter your email" required>
                  </div>
                  <div class="input-box">
                    <i class="fas fa-lock"></i>
                    <input type="password" id="password1" name="password1" placeholder="Enter your password" required>
                  </div>
                  <div class="input-box">
                    <i class="fas fa-lock"></i>
                    <input type="password" id="password2" name="password2" placeholder="Confirm password" required>
                  </div>
                  <div class="button input-box">
                    <input type="submit" id ="submit" name = "submit" Value="Sign Up">
                   
                  </div>
                  <div class="text sign-up-text">Already have an account? <label for="flip">Login now</label></div>
                </div>
          </form>
        </div>
        </div>
        </div>
      </div>
    </div>


{% endblock %}

website/templates/per_goals.html
{% extends "base.html" %} {% block title %}Pesonal Goals{% endblock %} {% block content
    %}
    
        {% block head %}
     
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
     
        <style media="screen">
    html{
        scroll-behavior: smooth;
    }     
    body{
        background-color:  #ab86ce;
    }
    .background{
        width: 430px;
        height: 520px;
        position: absolute;
        transform: translate(-50%,-50%);
        left: 50%;
        top: 50%;
        
    }
    
    form{
        height: 600px;
        width: 400px;
        background-color: rgba(255,255,255,0.13);
        position: absolute;
        transform: translate(-50%,-50%);
        top: 55%;
       
        left: 50%;
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 2px solid rgba(255,255,255,0.1);
        box-shadow: 0 0 40px rgba(8,7,16,0.6);
        padding: 50px 35px;
    }
    form *{
        font-family: 'Poppins',sans-serif;
        color: black;
        letter-spacing: 0.5px;
        outline: none;
        border: none;
    }
    
    
    input{
        display: block;
        height: 50px;
        width: 100%;
        background-color:whitesmoke;
        border-radius: 3px;
        padding: 0 10px;
        margin-top: 8px;
        font-size: 18px;
        font-weight: 300;
    }
            
    ::placeholder{
        color: black;
    }
    .button1{
        margin-top: 35px;
        width: 80%;
        margin-left: 34px;
        margin-bottom: 10px;
        background-color: rgb(60, 7, 104);
        color: #fdfdff;
        padding: 15px 0;
        font-size: 14px;
        font-weight: 600;
        border-radius: 5px;
        cursor: pointer;
    }
            label{
        display: block;
        margin-top: 10px;
        font-size: 16px;
        font-weight: 500;
    }
    
#per_goals {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 70%;
}

#per_goals td, #per_goals th {
  border: 1px solid #ddd;
  padding: 8px;
}

#per_goals tr:nth-child(even){background-color: #f2f2f2;}
#per_goals tr:nth-child(odd){background-color: #f3dbff;}

#per_goals tr:hover {background-color: #ddd;}

#per_goals th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #343a38;
  color: white;
}
    
    
        </style>
      {% endblock %}  

    <body>
        <div class="background">
            <div class="shape"></div>
            <div class="shape"></div>
        </div>      
                     <div id="form" class="card-body">
    
        <form method="POST">
         <h2>Enter Your Target</h2>
          <label>Goal</label>
          <input type="text" name="Goal" id="Goal" placeholder="Enter detail of goal">
          <label>Amount</label>
          <input type="text" name="Amount" id="Amount" placeholder="Enter amount">
          <label>Savings (Percentage of salary you want to save)</label>
          <input type="text" name = "Saving" id="Saving" placeholder="Default: 12% " />
         
          <button type="submit" class="button1">Submit</button>
          <button type="submit" class="button1" name="display" id="display" value="display" onclick="window.location.href = '#display_table';">Show My Goals</button>
        </form>
    
      </div>
      <div id ="display_table" style="margin-top: 700px;"align="center">
      {% if show %}
      <h2> My Goals</h2>
      <br>
        <table class="table table-striped" id="per_goals">
            <tr>
                <th style="text-align: center;">Goal Description</th>
                <th style="text-align: center;">Saving Amount</th>
                <th style="text-align: center;">Tenure Expected</th>
                <th style="text-align: center;">Tenure Actual</th>
                <th style="text-align: center;"></th>
            </tr>
            {% for goal in user.goals %}
            <tr>
               
                <td>{{ goal.details }}</td>
                <td>{{ goal.saving_amount }}</td>
                <td>{{ goal.tenure_expected }} months</td>
                <td>{{ goal.tenure_actual }} months</td>
                <td> <button type="button" class="close" onClick="deleteGoal({{ goal.id }})">
                    <span aria-hidden="true">&times;</span> </td>
                
            </tr>
            {% endfor %}
        </table>
        <div align="canter"> * Tenure expected is calculated on the basis of savings after expenditure of 30 days before the current date.</div>
        <br><br>
      {% endif %}
    </div>
    
    </body>
    
    {% endblock %}

    